### ISSUE TITLE
Migrate to AWS Go SDK v2

### ISSUE THREAD

**Issue by vrih** [bsm/bfs#39]
AWS Go SDK v2 went general availability on 2021-01-19. [Blog post](https://aws.amazon.com/blogs/developer/aws-sdk-for-go-version-2-general-availability/)

Benefits of migration should be:
- more sensible API
- more efficient calls

We should also review whether S3 Transfer Manager should be used.

**Comment by dim** [comment]
@mxmCherry assigned this to you, not very urgent, just something to keep on your radar

**Comment by mxmCherry** [comment]
@dim everything seems merged, tag/release?

**Comment by dim** [comment]
Done!
